create table if not exists public.flight_telemetry (
  id bigint generated by default as identity primary key,
  node_id text not null,
  vibr_x double precision not null,
  m_temp double precision not null,
  press double precision not null,
  cluster integer not null default 0,
  cluster_distance double precision not null default 0,
  ai_confidence double precision not null default 0,
  composite_trend_value double precision not null default 0,
  anomaly boolean not null default false,
  telemetry_quality text not null default 'verified',
  integrity text not null default 'verified',
  received_at timestamptz not null default now(),
  stored_at timestamptz not null default now()
);

create index if not exists flight_telemetry_received_at_idx
  on public.flight_telemetry (received_at desc);

create index if not exists flight_telemetry_node_received_at_idx
  on public.flight_telemetry (node_id, received_at desc);

alter table public.flight_telemetry enable row level security;

drop policy if exists "Service role can manage flight telemetry" on public.flight_telemetry;
create policy "Service role can manage flight telemetry"
  on public.flight_telemetry
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');
