create table if not exists public.organisations (
  id bigint generated by default as identity primary key,
  name text not null unique,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists organisations_name_idx
  on public.organisations (name);

alter table public.organisations enable row level security;

drop policy if exists "Service role can manage organisations" on public.organisations;
create policy "Service role can manage organisations"
  on public.organisations
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

insert into public.organisations (name)
values ('Aero-Mesh Operations')
on conflict (name) do nothing;

create table if not exists public.operators (
  id bigint generated by default as identity primary key,
  operator_id text not null unique,
  full_name text not null,
  organisation text not null default 'Aero-Mesh Operations',
  password_hash text not null,
  role text not null default 'operator',
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint operators_organisation_fkey
    foreign key (organisation)
    references public.organisations (name)
    on update cascade
);

alter table public.operators
  add column if not exists organisation text not null default 'Aero-Mesh Operations';

alter table public.operators
  add column if not exists password_hash text;

do $$
begin
  if not exists (select 1 from public.operators where password_hash is null) then
    alter table public.operators
      alter column password_hash set not null;
  end if;
end $$;

alter table public.operators
  add column if not exists role text not null default 'operator';

alter table public.operators
  add column if not exists status text not null default 'active';

alter table public.operators
  add column if not exists created_at timestamptz not null default now();

alter table public.operators
  add column if not exists updated_at timestamptz not null default now();

insert into public.organisations (name)
select distinct organisation
from public.operators
where organisation is not null
on conflict (name) do nothing;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'operators_organisation_fkey'
      and conrelid = 'public.operators'::regclass
  ) then
    alter table public.operators
      add constraint operators_organisation_fkey
      foreign key (organisation)
      references public.organisations (name)
      on update cascade;
  end if;
end $$;

create index if not exists operators_operator_id_idx
  on public.operators (operator_id);

create index if not exists operators_organisation_idx
  on public.operators (organisation);

alter table public.operators enable row level security;

drop policy if exists "Service role can manage operators" on public.operators;
create policy "Service role can manage operators"
  on public.operators
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

create table if not exists public.sessions (
  token text primary key,
  operator_id text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  constraint sessions_operator_id_fkey
    foreign key (operator_id)
    references public.operators (operator_id)
    on update cascade
    on delete cascade
);

create index if not exists sessions_operator_id_idx
  on public.sessions (operator_id);

create index if not exists sessions_expires_at_idx
  on public.sessions (expires_at);

alter table public.sessions enable row level security;

drop policy if exists "Service role can manage sessions" on public.sessions;
create policy "Service role can manage sessions"
  on public.sessions
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

create table if not exists public.security_incidents (
  id bigint generated by default as identity primary key,
  event_type text not null,
  severity text not null,
  source text not null,
  details text not null,
  buzzer_triggered boolean not null default false,
  led_triggered boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists security_incidents_created_at_idx
  on public.security_incidents (created_at desc);

create index if not exists security_incidents_severity_idx
  on public.security_incidents (severity);

alter table public.security_incidents enable row level security;

drop policy if exists "Service role can manage security incidents" on public.security_incidents;
create policy "Service role can manage security incidents"
  on public.security_incidents
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

create table if not exists public.flight_telemetry (
  id bigint generated by default as identity primary key,
  node_id text not null,
  vibr_x double precision not null,
  m_temp double precision not null,
  press double precision not null,
  altitude_ft double precision not null default 0,
  temp_location text not null default 'internal',
  cluster integer not null default 0,
  cluster_distance double precision not null default 0,
  ai_confidence double precision not null default 0,
  composite_trend_value double precision not null default 0,
  anomaly boolean not null default false,
  telemetry_quality text not null default 'verified',
  integrity text not null default 'verified',
  baseline_status text not null default 'nominal',
  baseline jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default now(),
  stored_at timestamptz not null default now()
);

alter table public.flight_telemetry
  add column if not exists altitude_ft double precision not null default 0,
  add column if not exists temp_location text not null default 'internal',
  add column if not exists baseline_status text not null default 'nominal',
  add column if not exists baseline jsonb not null default '{}'::jsonb;

create index if not exists flight_telemetry_received_at_idx
  on public.flight_telemetry (received_at desc);

create index if not exists flight_telemetry_node_received_at_idx
  on public.flight_telemetry (node_id, received_at desc);

alter table public.flight_telemetry enable row level security;

drop policy if exists "Service role can manage flight telemetry" on public.flight_telemetry;
create policy "Service role can manage flight telemetry"
  on public.flight_telemetry
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');
